name: Endor Labs Scan
on:
  workflow_dispatch:
    inputs:
      api:
        description: "Enter the target Endor Labs API"
        required: true
        type: choice
        default: https://api.endorlabs.com
        options:
        - https://api.staging.endorlabs.com
        - https://api.endorlabs.com
      tenant_name:
        description: "Enter your Endor Labs namespace?"
        required: true
        type: string
jobs:
  scan-repo:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
        - name: Setup namespace Environment Variables
          run: | 
            NAMESPACE=$(jq -r '.inputs.tenant_name' $GITHUB_EVENT_PATH)
            echo "::add-mask::$NAMESPACE" 
            echo NAMESPACE=$NAMESPACE >> $GITHUB_ENV
        
        - name: Checkout Repository
          uses: actions/checkout@v3
          
        - name: Setup dotnet
          uses: actions/setup-dotnet@v3
          with:
           dotnet-version: |
             6.0.x
           
        - name: Restore + Build .NET
          run: dotnet restore --use-lock-file && dotnet build

        - uses: actions/checkout@v3             
        - name: Build the Docker images 
          run: docker build ./VulnerableApp  --tag my-image-name:$(date +%s)   
          
            
        - name: Endor Labs Workflow Dispatch
          if: ${{ github.event_name == 'workflow_dispatch' }}
          uses: endorlabs/github-action@736c93ea52b002f2ac229aaeb273b102cbf6fe12
          with:
            namespace: ${{ github.event.inputs.tenant_name }}
            api_key: ${{ secrets.ENDOR_API_CREDENTIALS_KEY }}
            api_secret: ${{ secrets.ENDOR_API_CREDENTIALS_SECRET }}
            scan_summary_output_type: "table"
            pr: "false"
            enable_github_action_token: false
            scan_dependencies: "true"
            scan_secrets: "true"
            scan_git_logs: "true"
            additional_args: "--as-default-branch --api=${{ github.event.inputs.api }}"
