name: Mend Scan
on:
  workflow_dispatch:
env:
  DOCKER_IMAGE_NAME: "some-label"
  DOCKER_REPO_NAME: "publicvulnerableRepo"
  DOCKER_TAG: dev-${{ github.run_number }}
  MEND_USER_KEY: ${{ secrets.MEND_USER_KEY }}
  MEND_EMAIL: ${{ secrets.MEND_EMAIL }}
  MEND_URL: https://saas.mend.io

jobs:
  scan-repo:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
          
        - name: Setup dotnet
          uses: actions/setup-dotnet@v3
          with:
           dotnet-version: |
             6.0.x
           
        - name: Restore + Build .NET
          run: dotnet restore --use-lock-file && dotnet build

        - name: Build the Docker images 
          uses: docker/build-push-action@v4
          with:
            context: .
            push: false
            tags: "my-image-name"
            labels: "some-label"        
            
        - name: Download Mend CLI & Run a Scan   
          run: |
           echo $DOCKER_IMAGE_NAME && mend auth info && curl https://downloads.mend.io/cli/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
           mend image "my-image-name" --format sarif --filename results.sarif --local-pull
      
        - name: Upload sarif
          uses: github/codeql-action/upload-sarif@v3
          with:
           sarif_file: results.sarif
